### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by victoraugustolls** [frigus02/opentelemetry-application-insights#15]
I know opening an issue for this is not ideal, but I had to. Just wanted to thank you for this crate. I'm new to rust but have been developing on Go and Python for a long time, and one of the necessary features that I need to start developing (at work) apis with rust is been apple to integrate with Application Insights, so thanks a lot!

As I said, I'm new to rust, but as soon as I think that I'm proficient enough with it, I hope that I can help you here!

**Comment by frigus02** [comment]
Thanks a lot. It's great to hear that this is helpful to someone else, too.

I just started using Application Insights myself. So if anything seems off or data could be represented better in Application Insights, please feel free to open an issue. 🙂

**Comment by victoraugustolls** [comment]
Will do!
