### ISSUE TITLE
Should the endpoint be hardcoded?

### ISSUE THREAD

**Issue by twitchax** [frigus02/opentelemetry-application-insights#20]
It looks like the ingestion endpoint is hardcoded: https://github.com/frigus02/opentelemetry-application-insights/blob/main/src/uploader.rs#L7.

Does this work if my ingestion endpoint is different?  My ingestion endpoint is `https://westus2-0.in.applicationinsights.azure.com/`, and it doesn't look like any of the traces are coming through.

**Comment by frigus02** [comment]
Oh, oops. I didn't know the endpoint could be different. That's probably why you don't see anything coming through. We should make the endpoint configurable.

Do you want to make a PR for that? Otherwise I might get to this in the evening.

**Comment by twitchax** [comment]
I don't mind taking a stab at it, but it will be a few days until I get to it.

**Comment by frigus02** [comment]
I pushed version 0.7.0, which lets you configure the endpoint
