### ISSUE TITLE
Appears as though timings are off by a factor of ten.

### ISSUE THREAD

**Issue by twitchax** [frigus02/opentelemetry-application-insights#23]
I have instrumented my request through both the browser, and my server.

The server, and the browser, report almost identical results.

Here is the browser.
![image](https://user-images.githubusercontent.com/549523/100984459-9a99af00-34ff-11eb-8b97-7d3d992114ae.png)

Here is the server.
![image](https://user-images.githubusercontent.com/549523/100984482-a2f1ea00-34ff-11eb-8192-b02fa6313a22.png)

However, this same trace in app insights is reported as a factor of ten less (I have tested this 5 times...same result each time).

Here is app insights.
![image](https://user-images.githubusercontent.com/549523/100984527-b1400600-34ff-11eb-91c5-5c1a1a8c1c67.png)

Looking through the code, it looks like you just take the delta, and then convert to a string.  Is it possible that app insights is interpreting this string incorrectly?

**Comment by frigus02** [comment]
Hm, good find. I have to admin, I don't remember verifying the duration in App Insights properly. So it's possible to conversion is wrong:

https://github.com/frigus02/opentelemetry-application-insights/blob/de667a81481a9764dc71f8ac81da55744b887dae/src/convert.rs#L17-L28

I'm going to add a few more tests to check.

**Comment by twitchax** [comment]
I figured it out: sending a PR.

**Comment by frigus02** [comment]
I just published version 0.7.1 with your fix. Thanks again for finding and fixing this 👍
