### ISSUE TITLE
`opentelemetry::sdk::Provider::Resource` not being added to each Span/Event

### ISSUE THREAD

**Issue by tot0** [frigus02/opentelemetry-application-insights#3]
The `opentelemetry-zipkin` exporter does it [here](https://github.com/open-telemetry/opentelemetry-rust/blob/a5523ae8673a7f7105c0145200082ab821c0b14f/opentelemetry-zipkin/src/lib.rs#L217).

I think it could be done in `opentelemetry-application-insights` like this:

```rust
impl Exporter {
   ....
   fn create_envelopes(...) ... {
      ...
      let mut attrs = evictedhashmap_to_hashmap(&span.attributes);
      for (k, v) in span.resource.iter() {
          attrs.insert(k.as_str(), v);
      }
```

If this sounds good then I can open a PR today.

Cheers!

**Comment by frigus02** [comment]
Oh yeah, I completely missed that. Thank for reporting and thanks for the pull request.

**Comment by frigus02** [comment]
I just pushed version 0.1.2 to crates.io. Thanks again for your help 👍

**Comment by tot0** [comment]
Thank you for merging and releasing so quickly :)
