### ISSUE TITLE
How to push data to traces instead of dependencies?

### ISSUE THREAD

**Issue by christopher-wilke** [frigus02/opentelemetry-application-insights#60]
All data seems to be exported to the App Insights `dependencies` table. How can I export it to `traces`?

**Comment by frigus02** [comment]
You can see how spans and events are mapped here: https://docs.rs/opentelemetry-application-insights/latest/opentelemetry_application_insights/#attribute-mapping

Spans are exported either as dependencies or requests depending on the span kind.

Events are exported either as exceptions, events or traces depending on different event attributes.

Does this help?

**Comment by christopher-wilke** [comment]
Thx for your quick feedback! 👍 

Can you maybe share a simple example how to create an event that gets exported as Application Insights Trace? Thanks in advance.

**Comment by frigus02** [comment]
Sure, you can run the attributes example from this repo.

```
INSTRUMENTATION_KEY=<key> cargo run --example attributes
```

This event is logged as a trace:

https://github.com/frigus02/opentelemetry-application-insights/blob/15be4bcdb2b0dc6ee1b10fd9205f30d70c18e397/examples/attributes.rs#L14

**Comment by christopher-wilke** [comment]
Works like a charm. Thank you very much!

Btw, great Rust skills! I already learned a lot from you.
