### ISSUE TITLE
Opentelemetry semantic conventions for databases are out of date

### ISSUE THREAD

**Issue by johnchildren** [frigus02/opentelemetry-application-insights#7]
Hi, it looks like the opentelemetry databases semantic conventions have changed recently. Little bit annoying but easily fixable I think.

https://github.com/open-telemetry/opentelemetry-specification/commit/6c86748a63e9e7194f414b8175356a35e75b9400#diff-704a6b627a90b3570049b96aac53c906

I can make a PR updating the fields that have changed if necessary, but this seems a bit annoying for users who may be using the previous conventions.

**Comment by johnchildren** [comment]
https://github.com/frigus02/opentelemetry-application-insights/pull/8

**Comment by frigus02** [comment]
Hi John. Yeah, these changes are going to be a bit annoying for existing users of the library.

Given that the spec is still in beta, I guess those change are somehow expected. So I think I'm happy to just change this here to follow the latest spec and add some obvious breaking change note to the changelog to indicate what upgrading users will have to do.
