### ISSUE TITLE
Support for opentelemetry-appender-log

### ISSUE THREAD

**Issue by llamington** [frigus02/opentelemetry-application-insights#80]
Is there currently any ability to support exporting logs through `opentelemetry-appender-log`? This crate does not seem to expose a `LogExporter`.

**Comment by frigus02** [comment]
Ah yes. Log export is not supported, yet. We can probably implement that based similar to https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/monitor/monitor-opentelemetry-exporter/src/utils/logUtils.ts

**Comment by llamington** [comment]
Please let me know if you would like a hand with anything regarding this issue

**Comment by frigus02** [comment]
I will probably continue working on this on the weekend. If you like to test the current state and add some tests (e.g. in tests/http_request.rs) or examples, I'll happily take those :-). Could be a PR to the logs branch.

**Comment by frigus02** [comment]
I pushed version 0.33.0 to crates.io, which supports log export.
