### ISSUE TITLE
Top-level events not being sent to AI

### ISSUE THREAD

**Issue by iensu** [frigus02/opentelemetry-application-insights#88]
Hi! 

I noticed we were missing some logs in application insights and noticed that "top-level" events are not being sent to AI. I assume it's because they're not part of any explicit span. Is this a bug or intended behavior? Or is our tracing configuration incorrect? 

When using the `tracing_subscriber` format layers top-level events are exported and printed to stdout, so we expected the same behavior by `opentelemetry-application-insights`. 

`tracing_subscriber::fmt::layer` configuration:

```rust
let layer = tracing_subscriber::fmt::layer::<Registry>()
            .pretty()
            .with_line_number(true)
            .with_file(true)
            .with_thread_names(true)
            .with_filter(filter)
            .boxed();
```

Simplified version of our application insights tracing setup:

```rust
#[tokio::main]
async fn main() {
    setup_tracing();

    tracing::info!("Will NOT be sent to Application Insights!");

    tracing::info_span!("A span")
        .in_scope(|| tracing::info!("Will be sent to Application Insights"));
    
    start_server().await;
}

fn setup_tracing() {
    let tracer =
        opentelemetry_application_insights::new_pipeline_from_connection_string(connection_string)
            .expect("invalid valid appinsights connection string")
            .with_client(reqwest::Client::default())
            .with_service_name("my-api")
            .install_batch(sdk::runtime::Tokio);

    let layer = tracing_opentelemetry::layer()
        .with_error_fields_to_exceptions(true)
        .with_error_records_to_exceptions(true)
        .with_tracer(tracer)
        .with_filter(filter)
        .boxed();

    let subscriber = tracing_subscriber::registry().with(vec![layer]);

    tracing::subscriber::set_global_default(subscriber).unwrap();
}

#[tracing::instrument()]
async fn start_server() {
    // ...
}

```

**Comment by frigus02** [comment]
This is probably a question for the `tracing-opentelemetry` maintainers. But reading the code, I think that's by design:

https://github.com/tokio-rs/tracing-opentelemetry/blob/7c1fc95904b71cf98751480b413064f3108b93f4/src/layer.rs#L979-L980

That said, I don't see this being documented anywhere. I suggest opening an issue over on https://github.com/tokio-rs/tracing-opentelemetry. It might make sense to make this behaviour more obvious in the docs/readme.

**Comment by iensu** [comment]
Thank you, will do!
